[package]
name = "vibespeak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.4"
vosk = "0.3.1"
