[commands]
# --- Tmux Control (prefix is C-a) ---
"split pane"         = "xdotool key ctrl+a bar"            
"vertical split"     = "xdotool key ctrl+a minus"          
"new window"         = "xdotool key ctrl+a c"              
"reload tmux"        = "xdotool key ctrl+a r"              
"next pane"          = "xdotool key ctrl+a o"              
"last pane"          = "xdotool key ctrl+a semicolon"      
"next window"        = "xdotool key ctrl+a n"              
"previous window"    = "xdotool key ctrl+a p"              
"pane zero"          = "xdotool key ctrl+a 0"
"pane one"           = "xdotool key ctrl+a 1"
"pane two"           = "xdotool key ctrl+a 2"
"pane three"         = "xdotool key ctrl+a 3"
"pane four"          = "xdotool key ctrl+a 4"
"pane five"          = "xdotool key ctrl+a 5"
"pane six"           = "xdotool key ctrl+a 6"
"pane seven"         = "xdotool key ctrl+a 7"
"pane eight"         = "xdotool key ctrl+a 8"
"pane nine"          = "xdotool key ctrl+a 9"
"maximize pane"      = "xdotool key ctrl+a m"             
"tmux cht"           = "xdotool key ctrl+a i"             
"pane left"          = "xdotool key ctrl+a h"
"pane down"          = "xdotool key ctrl+a j"
"pane up"            = "xdotool key ctrl+a k"
"pane right"         = "xdotool key ctrl+a l"
"resize left"        = "xdotool key ctrl+a H"
"resize down"        = "xdotool key ctrl+a J"
"resize up"          = "xdotool key ctrl+a K"
"resize right"       = "xdotool key ctrl+a L"

# --- Quick pane layout ---
"even horizontal"    = "xdotool key ctrl+a quotedbl"     
"even vertical"      = "xdotool key ctrl+a percent"      

# --- General Shell ---
"clear"              = "xdotool type 'clear'; xdotool key Return"
"list"               = "xdotool type 'ls'; xdotool key Return"
"show history"       = "xdotool type 'history'; xdotool key Return"
"open htop"          = "xdotool type 'htop'; xdotool key Return"

# --- Alacritty Font Zoom ---
"zoom in"            = "xdotool key ctrl+KP_Add"        
"zoom out"           = "xdotool key ctrl+minus"
"reset zoom"         = "xdotool key ctrl+0"

# --- i3 Window Manager ---
"workspace one"         = "i3-msg workspace 1"
"workspace two"         = "i3-msg workspace 2"
"workspace three"       = "i3-msg workspace 3"
"workspace four"        = "i3-msg workspace 4"
"move left"             = "i3-msg focus left"
"move right"            = "i3-msg focus right"
"move up"               = "i3-msg focus up"
"move down"             = "i3-msg focus down"
"full"                  = "i3-msg fullscreen toggle"
"floating"              = "i3-msg floating toggle, resize set 1720 1020, move position center"
"split vertical"        = "i3-msg split v"
"split horizontal"      = "i3-msg split h"
"close window"          = "i3-msg kill"
"move to workspace one" = "i3-msg move container to workspace 1"
"move to workspace two" = "i3-msg move container to workspace 2"
"reload"                = "i3-msg reload"

# --- Browser ---
"next tab"              = "xdotool key ctrl+Tab"
"previous tab"          = "xdotool key ctrl+shift+Tab"
"close tab"             = "xdotool key ctrl+w"
"new tab"               = "xdotool key ctrl+t"

# --- Neovim ---
"save file"             = "xdotool key Escape colon w Return"
"quit nvim"             = "xdotool key Escape colon q Return"
"write and quit"        = "xdotool key Escape colon w q Return"
"open file"             = "xdotool type ':e '"
"next buffer"           = "xdotool key Escape colon b n Return"
"previous buffer"       = "xdotool key Escape colon b p Return"
"close buffer"          = "xdotool key Escape colon b d Return"
"go to normal mode"     = "xdotool key Escape"
"go to insert mode"     = "xdotool key i"
"go to visual mode"     = "xdotool key v"
"find in file"          = "xdotool key Escape slash"

# --- General Shortcuts ---
"lock screen"           = "i3lock"
"terminal"              = "alacritty"
"browser"               = "firefox"
"show dmenu"            = "dmenu_run"
"take screenshot"       = "scrot"
"open files"            = "thunar"
"down"                  = "xdotool key Down"
"up"                    = "xdotool key Up"
"bottom"                = "xdotool key End"
"top"                   = "xdotool key Home"
