[commands]
"type" = ""
# --- Tmux Control ---
"pane split"      = "xdotool key ctrl+a bar"
"pane vsplit"     = "xdotool key ctrl+a minus"
"pane win"        = "xdotool key ctrl+a c"
"pane reload"     = "xdotool key ctrl+a r"
"win next"        = "xdotool key ctrl+a n"
"win prev"        = "xdotool key ctrl+a p"
"pane zero"       = "xdotool key ctrl+a 0"
"pane one"        = "xdotool key ctrl+a 1"
"pane two"        = "xdotool key ctrl+a 2"
"pane three"      = "xdotool key ctrl+a 3"
"pane four"       = "xdotool key ctrl+a 4"
"pane five"       = "xdotool key ctrl+a 5"
"pane six"        = "xdotool key ctrl+a 6"
"pane seven"      = "xdotool key ctrl+a 7"
"pane eight"      = "xdotool key ctrl+a 8"
"pane nine"       = "xdotool key ctrl+a 9"
"pane max"        = "xdotool key ctrl+a m"
"pane cht"        = "xdotool key ctrl+a i"
"pane left"       = "xdotool key ctrl+a h"
"pane down"       = "xdotool key ctrl+a j"
"pane up"         = "xdotool key ctrl+a k"
"pane right"      = "xdotool key ctrl+a l"
"pane lresize"    = "xdotool key ctrl+a H"
"pane dresize"    = "xdotool key ctrl+a J"
"pane uresize"    = "xdotool key ctrl+a K"
"pane rresize"    = "xdotool key ctrl+a L"
"pane horz"       = "xdotool key ctrl+a quotedbl"
"pane vert"       = "xdotool key ctrl+a percent"

# --- Dev Commands ---
"dev watch"       = "tmux send-keys -t 1 'cargo leptos watch' C-m"
"dev check"       = "tmux send-keys -t 1 'cargo check' C-m"
"dev style"       = "tmux send-keys -t 2 'yarn dev' C-m"

# --- Shell ---
"clear"     = "xdotool type 'clear'; xdotool key Return"
"list"      = "xdotool type 'ls'; xdotool key Return"
"history"   = "xdotool type 'history'; xdotool key Return"
"htop"      = "xdotool type 'htop'; xdotool key Return"
"neo"      = "xdotool type 'nvim'; xdotool key Return"
"info"     = "xdotool type 'fastfetch'; xdotool key Return"

# --- Alacritty Font Zoom ---
"zoom in"         = "xdotool key ctrl+KP_Add"
"zoom out"        = "xdotool key ctrl+minus"
"zoom reset"      = "xdotool key ctrl+0"

# --- i3 Window Manager ---
"desk one"        = "i3-msg workspace 1"
"desk two"        = "i3-msg workspace 2"
"desk three"      = "i3-msg workspace 3"
"desk four"       = "i3-msg workspace 4"
"desk left"       = "i3-msg focus left"
"desk right"      = "i3-msg focus right"
"desk up"         = "i3-msg focus up"
"desk down"       = "i3-msg focus down"
"desk full"       = "i3-msg fullscreen toggle"
"desk float"      = "i3-msg floating toggle, resize set 1720 1020, move position center"
"desk splitv"     = "i3-msg split v"
"desk splith"     = "i3-msg split h"
"desk kill"       = "i3-msg kill"
"desk moveone"    = "i3-msg move container to workspace 1"
"desk movetwo"    = "i3-msg move container to workspace 2"
"desk reload"     = "i3-msg reload"

# --- Browser ---
"browser newtab"  = "xdotool key ctrl+t"
"browser closetab"= "xdotool key ctrl+w"
"browser nexttab" = "xdotool key ctrl+Tab"
"browser prevtab" = "xdotool key ctrl+shift+Tab"

# --- Scrolling ---
"scroll down"     = "for i in {1..10}; do xdotool key Down; done"
"scroll up"       = "for i in {1..10}; do xdotool key Up; done"
"scroll pagedown" = "xdotool key space"
"scroll pageup"   = "xdotool key shift+space"

# --- Neovim ---
"neo save"        = "xdotool key Escape colon w Return"
"neo saveall"     = "xdotool key Escape colon w a Return"
"neo quit"        = "xdotool key Escape colon q Return"
"neo quitall"     = "xdotool key Escape colon q a Return"
"neo open"        = "xdotool key space f f"
"neo nextbuf"     = "xdotool key Escape colon b n Return"
"neo prevbuf"     = "xdotool key Escape colon b p Return"
"neo closebuf"    = "xdotool key Escape colon b d Return"
"neo normal"      = "xdotool key Escape"
"neo insert"      = "xdotool key i"
"neo visual"      = "xdotool key v"
"neo find"        = "xdotool key Escape slash"
"neo restore"     = "xdotool key space w r"
"neo down"    = "xdotool key ctrl+d"    
"neo up"      = "xdotool key ctrl+u"    
# "up"    = "xdotool key ctrl+y"    
# "down"  = "xdotool key ctrl+e"    

# --- General Shortcuts ---
"system lock"     = "i3lock"
"system term"     = "alacritty"
"system browser"  = "firefox"
"system menu"     = "dmenu_run"
"system files"    = "thunar"
"system end"      = "xdotool key End"
"system home"     = "xdotool key Home"
