[commands]
"type" = ""

# --- Tmux Control (pane/window) ---
"split pane"       = "xdotool key ctrl+a bar"
"split vertical"   = "xdotool key ctrl+a minus"
"new window"       = "xdotool key ctrl+a c"
"reload tmux"      = "xdotool key ctrl+a r"
"next window"      = "xdotool key ctrl+a n"
"previous window"  = "xdotool key ctrl+a p"
"pane zero"        = "xdotool key ctrl+a 0"
"pane one"         = "xdotool key ctrl+a 1"
"pane two"         = "xdotool key ctrl+a 2"
"pane three"       = "xdotool key ctrl+a 3"
"pane four"        = "xdotool key ctrl+a 4"
"pane five"        = "xdotool key ctrl+a 5"
"pane six"         = "xdotool key ctrl+a 6"
"pane seven"       = "xdotool key ctrl+a 7"
"pane eight"       = "xdotool key ctrl+a 8"
"pane nine"        = "xdotool key ctrl+a 9"
"maximize pane"    = "xdotool key ctrl+a m"
"copy mode"        = "xdotool key ctrl+a i"
"move left"        = "xdotool key ctrl+a h"
"move down"        = "xdotool key ctrl+a j"
"move up"          = "xdotool key ctrl+a k"
"move right"       = "xdotool key ctrl+a l"
"resize left"      = "xdotool key ctrl+a H"
"resize down"      = "xdotool key ctrl+a J"
"resize up"        = "xdotool key ctrl+a K"
"resize right"     = "xdotool key ctrl+a L"
"split horizontal" = "xdotool key ctrl+a quotedbl"
"split percent"    = "xdotool key ctrl+a percent"

# --- Dev/terminal commands ---
"start dev"        = "tmux send-keys -t 1 'cargo leptos watch' C-m"
"check code"       = "tmux send-keys -t 1 'cargo check' C-m"
"start style"      = "tmux send-keys -t 2 'yarn dev' C-m"

# --- Shell ---
"clear screen"     = "xdotool type 'clear'; xdotool key Return"
"list files"       = "xdotool type 'ls'; xdotool key Return"
"show history"     = "xdotool type 'history'; xdotool key Return"
"show processes"         = "xdotool type 'htop'; xdotool key Return"
"open editor"      = "xdotool type 'nvim'; xdotool key Return"
"show info"        = "xdotool type 'fastfetch'; xdotool key Return"

# --- Alacritty Font Zoom ---
"zoom in"          = "xdotool key ctrl+KP_Add"
"zoom out"         = "xdotool key ctrl+minus"
"reset zoom"       = "xdotool key ctrl+0"

# --- i3 Window Manager ---
"desk one"    = "i3-msg workspace 1"
"desk two"    = "i3-msg workspace 2"
"desk three"  = "i3-msg workspace 3"
"desk four"   = "i3-msg workspace 4"
"focus left"       = "i3-msg focus left"
"focus right"      = "i3-msg focus right"
"focus up"         = "i3-msg focus up"
"focus down"       = "i3-msg focus down"
"full screen"      = "i3-msg fullscreen toggle"
"float window"     = "i3-msg floating toggle, resize set 1720 1020, move position center"
"close window"     = "i3-msg kill"
"move to one"      = "i3-msg move container to workspace 1"
"move to two"      = "i3-msg move container to workspace 2"
"reload windows"   = "i3-msg reload"

# --- Browser ---
"new tab"          = "xdotool key ctrl+t"
"close tab"        = "xdotool key ctrl+w"
"next tab"         = "xdotool key ctrl+Tab"
"previous tab"     = "xdotool key ctrl+shift+Tab"

# --- Scrolling ---
"scroll down"      = "for i in {1..10}; do xdotool key Down; done"
"scroll up"        = "for i in {1..10}; do xdotool key Up; done"
"page down"        = "xdotool key space"
"page up"          = "xdotool key shift+space"

# --- Neovim ---
"save file"        = "xdotool key Escape colon w Return"
"save all"         = "xdotool key Escape colon w a Return"
"quit file"        = "xdotool key Escape colon q Return"
"quit all"         = "xdotool key Escape colon q a Return"
"open file"        = "xdotool key space f f"
"next buffer"      = "xdotool key Escape colon b n Return"
"previous buffer"  = "xdotool key Escape colon b p Return"
"close buffer"     = "xdotool key Escape colon b d Return"
"normal mode"      = "xdotool key Escape"
"insert mode"      = "xdotool key i"
"visual mode"      = "xdotool key v"
"find text"        = "xdotool key Escape slash"
"restore window"   = "xdotool key space w r"
"page down file"   = "xdotool key ctrl+d"
"page up file"     = "xdotool key ctrl+u"

# --- General Shortcuts ---
"lock screen"      = "i3lock"
"open terminal"    = "alacritty"
"open browser"     = "firefox"
"show menu"        = "dmenu_run"
"open files"       = "ranger"
"go to end"        = "xdotool key End"
"go to home"       = "xdotool key Home"
